# Generated by Django 5.2.7 on 2025-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id_modelo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'modelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgresoServicio',
            fields=[
                ('id_prog_serv', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('porcentaje', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evidencia_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'progreso_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id_propietario', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'propietarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id_reservacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('id_estado', models.BigIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('avance_global', models.IntegerField(blank=True, null=True)),
                ('estado_global', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosReservados',
            fields=[
                ('id_serv_res', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('avance_porcentaje', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios_reservados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosTaller',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_estado', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposUsuarios',
            fields=[
                ('id_tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
    ]
