# Generated by Django 5.2.7 on 2025-11-06 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('capacidad', models.IntegerField(default=1)),
                ('reservaciones_actuales', models.IntegerField(default=0)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_creados', to=settings.AUTH_USER_MODEL)),
                ('reservacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horario_asignado', to='agencia.reservacion')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Horario',
                'verbose_name_plural': 'Disponibilidades de Horarios',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.AddField(
            model_name='reservacion',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservaciones', to='agencia.disponibilidadhorario'),
        ),
    ]
